#!/usr/bin/env python3
# Generates the raylib bindings in src/ from tools/raylib_api.json, the API
# description raylib ships in tools/rlparser/output (6.0's has unescaped quotes in the
# description of LoadDirectoryFilesEx; this copy escapes them). Run from the repository root:
#
#   python3 tools/generate.py
#
# Structs, enums, colors and every extern come from the description; so do the
# public wrappers of functions that only take and return values. Functions
# that need pointers are wrapped by hand in the other files of src/.

import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
API = json.load(open(os.path.join(ROOT, "tools", "raylib_api.json")))
HEADER = "// Generated by tools/generate.py from raylib_api.json (raylib {}). Do not edit.\n".format(
    next(d["value"] for d in API["defines"] if d["name"] == "RAYLIB_VERSION"))

STRUCTS = {s["name"]: s for s in API["structs"]}
ALIASES = {a["name"]: a["type"] for a in API["aliases"] if not a["name"].startswith("*")}
# ModelAnimPose is `Transform *`
POINTER_ALIASES = {"ModelAnimPose"}
# Bit flags: plain constants, since they are combined with `|`
FLAG_ENUMS = {"ConfigFlags", "Gesture"}
ENUMS = {e["name"]: e for e in API["enums"] if e["name"] not in FLAG_ENUMS}

NUMBERS = {
    "int": "i32",
    "unsigned int": "u32",
    "float": "f32",
    "double": "f64",
    "unsigned char": "u8",
    "char": "u8",
    "bool": "bool",
}

# Parameter names valk would not accept
RENAME = {}
ENUM_MEMBER_RENAME = {"null": "none"}

# Whose int parameters are really an enum: (function pattern, parameter) -> enum
ENUM_PARAMS = [
    (r".*", "key", "KeyboardKey"),
    (r"^IsMouseButton", "button", "MouseButton"),
    (r"^IsGamepadButton", "button", "GamepadButton"),
    (r"^GetGamepadAxis", "axis", "GamepadAxis"),
    (r"^SetMouseCursor$", "cursor", "MouseCursor"),
    (r"^UpdateCamera$", "mode", "CameraMode"),
    (r"^BeginBlendMode$", "mode", "BlendMode"),
    (r"^SetTraceLogLevel$", "logLevel", "TraceLogLevel"),
    (r"^SetTextureFilter$", "filter", "TextureFilter"),
    (r"^SetTextureWrap$", "wrap", "TextureWrap"),
    (r"^LoadTextureCubemap$", "layout", "CubemapLayout"),
    (r"^ImageFormat$", "newFormat", "PixelFormat"),
    (r"^(LoadImageRaw|GetPixelDataSize|GetPixelColor|SetPixelColor)$", "format", "PixelFormat"),
    (r"^SetMaterialTexture$", "mapType", "MaterialMapIndex"),
    (r"^SetShaderValue", "uniformType", "ShaderUniformDataType"),
]

# String arguments where NULL asks for raylib's default; an empty string sends it
NULLABLE_STRINGS = {
    ("LoadShader", "vsFileName"), ("LoadShader", "fsFileName"),
    ("LoadShaderFromMemory", "vsCode"), ("LoadShaderFromMemory", "fsCode"),
}

# In-place functions become methods of the struct their first pointer argument names
METHOD_NAMES = {
    "UpdateCamera": "update",
    "UpdateCameraPro": "update_pro",
    "GenTextureMipmaps": "gen_mipmaps",
    "UploadMesh": "upload",
    "GenMeshTangents": "gen_tangents",
    "SetMaterialTexture": "set_texture",
    "SetModelMeshMaterial": "set_mesh_material",
    "ImageFormat": "convert_format",
    "WaveFormat": "convert_format",
    "ImageToPOT": "to_pot",
    "ImageMipmaps": "gen_mipmaps",
}

# The structs raylib changes in place through a pointer
METHOD_STRUCTS = {"Image", "Camera3D", "Texture", "Mesh", "Material", "Model", "Wave"}

# Left out of the bindings: callbacks, C varargs, `long`, and text helpers
# that valk's String already covers
SKIP_PREFIXES = ("Text", "LoadUTF8", "UnloadUTF8", "LoadCodepoints", "UnloadCodepoints",
                 "GetCodepoint", "CodepointToUTF8", "LoadTextLines", "UnloadTextLines", "GetTextBetween")


# An int parameter that says how many elements the pointer before it has
def is_count(param):
    if param is None or param["type"] != "int":
        return False
    name = param["name"].lower()
    return name.endswith("count") or name == "instances"


def snake(name):
    name = re.sub(r"([a-z])([23])D", r"\1_\2d", name)
    name = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", name)
    name = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", name)
    return name.lower()


def arg_name(name):
    name = snake(name)
    return RENAME.get(name, name)


def resolve(name):
    while name in ALIASES:
        name = ALIASES[name]
    return name


def doc(text, indent=""):
    text = text.strip()
    if not text:
        return ""
    text = text[0].upper() + text[1:]
    if not text.endswith("."):
        text += "."
    return indent + "/// " + text + "\n"


def field_type(ctype):
    m = re.match(r"^(.*)\[(\d+)\]$", ctype)
    if m:
        return "[{} x {}]".format(field_type(m.group(1).strip()), m.group(2))
    if ctype.endswith("*") or ctype in POINTER_ALIASES:
        return "?ptr"
    if ctype in NUMBERS:
        return NUMBERS[ctype]
    return resolve(ctype)


def field_default(vtype):
    if vtype == "?ptr":
        return "null"
    if vtype == "bool":
        return "false"
    if vtype.startswith("["):
        return None
    if vtype in NUMBERS.values():
        return "0"
    return ".{}"


def enum_prefix(names):
    prefix = os.path.commonprefix(names)
    return prefix[: prefix.rfind("_") + 1]


def enum_members(enum):
    names = [v["name"] for v in enum["values"]]
    prefix = enum_prefix(names) if len(names) > 1 else names[0][: names[0].rfind("_") + 1]
    out = []
    for v in enum["values"]:
        member = v["name"][len(prefix):].lower()
        out.append((ENUM_MEMBER_RENAME.get(member, member), v))
    return out


def write(path, text):
    with open(os.path.join(ROOT, "src", path), "w") as f:
        f.write(text)


################################################################
# Types, enums and colors
################################################################

def gen_types():
    out = [HEADER]
    for s in API["structs"]:
        out.append("\n" + doc(s["description"]))
        out.append("+ struct {} {{\n".format(s["name"]))
        for f in s["fields"]:
            vtype = field_type(f["type"])
            default = field_default(vtype)
            out.append(doc(f["description"], "    "))
            line = "    + {}: {}".format(snake(f["name"]), vtype)
            if default is not None:
                line += " ({})".format(default)
            out.append(line + "\n")
        out.append("}\n")
    out.append("\n")
    for a in API["aliases"]:
        if a["name"].startswith("*"):
            continue
        out.append(doc(a["description"]))
        out.append("+ alias {} for {}\n".format(a["name"], a["type"]))
    write("types.valk", "".join(out))


def gen_enums():
    out = [HEADER]
    for e in API["enums"]:
        if e["name"] in FLAG_ENUMS:
            out.append("\n// " + e["description"] + "\n")
            for v in e["values"]:
                out.append(doc(v["description"]))
                out.append("+ value {} ({})\n".format(v["name"], hex(v["value"])))
            continue
        out.append("\n" + doc(e["description"]))
        out.append("+ enum {} : i32 {{\n".format(e["name"]))
        for member, v in enum_members(e):
            out.append(doc(v["description"], "    "))
            out.append("    {} ({})\n".format(member, v["value"]))
        out.append("}\n")

    out.append("\n// Colors\n")
    for d in API["defines"]:
        if d["type"] != "COLOR":
            continue
        rgba = [int(x) for x in re.findall(r"\d+", d["value"])]
        out.append("/// {}\n".format(d.get("description", d["name"]).strip() or d["name"]))
        out.append("+ value {} (Color{{ r: {}, g: {}, b: {}, a: {} }})\n".format(d["name"], *rgba))

    out.append("\n/// raylib's version, as a string.\n")
    out.append('+ value RAYLIB_VERSION ("{}")\n'.format(next(d["value"] for d in API["defines"] if d["name"] == "RAYLIB_VERSION")))
    out.append("/// Pi.\n+ value PI (3.14159265358979323846)\n")
    out.append("/// Multiply degrees by this for radians.\n+ value DEG2RAD (PI / 180.0)\n")
    out.append("/// Multiply radians by this for degrees.\n+ value RAD2DEG (180.0 / PI)\n")
    write("enums.valk", "".join(out))


################################################################
# Externs
################################################################

# `many`: the pointer is to an array, its count follows
def extern_type(ctype, many=False):
    ctype = ctype.strip()
    if ctype == "void":
        return "void"
    if ctype in ("const char *", "char *"):
        return "?cstring"
    m = re.match(r"^(?:const )?(\w+) \*$", ctype)
    if m and resolve(m.group(1)) in STRUCTS:
        return ("?*[{}]" if many else "?*{}").format(resolve(m.group(1)))
    if m and many and m.group(1) in ("int", "float"):
        return "?*[{}]".format(NUMBERS[m.group(1)])
    if ctype.endswith("*"):
        return "?ptr"
    if ctype in NUMBERS:
        return NUMBERS[ctype]
    if resolve(ctype) in STRUCTS:
        return resolve(ctype)
    return None


def bindable(f):
    if f["returnType"] == "long":
        return False
    for p in f.get("params", []):
        if p["type"] in ("...", "long", "va_list") or p["type"].endswith("Callback"):
            return False
    return True


def gen_externs():
    out = [HEADER, "\n// The C functions, as raylib exports them. The package wraps them.\n\n"]
    out.append("// Windows links raylib.dll through its import library, raylibdll.lib\n")
    out.append('#if OS == "win"\n')
    out.append('link "raylibdll"\n')
    out.append("#else\n")
    out.append('link "raylib"\n')
    out.append("#end\n\n")
    for f in API["functions"]:
        if not bindable(f):
            continue
        args = []
        params = f.get("params", [])
        for i, p in enumerate(params):
            nxt = params[i + 1] if i + 1 < len(params) else None
            t = extern_type(p["type"], is_count(nxt))
            if t is None:
                raise Exception("unmapped {} in {}".format(p["type"], f["name"]))
            args.append("{}: {}".format(arg_name(p["name"]), t))
        ret = extern_type(f["returnType"])
        if ret is None:
            raise Exception("unmapped return {} in {}".format(f["returnType"], f["name"]))
        out.append("extern fn {}({}) {};\n".format(f["name"], ", ".join(args), ret))
    write("extern.valk", "".join(out))


################################################################
# Public wrappers
################################################################

def enum_for(fname, pname):
    for pattern, param, enum in ENUM_PARAMS:
        if param == pname and re.search(pattern, fname):
            return enum
    return None


def value_type(ctype):
    if ctype in NUMBERS:
        return NUMBERS[ctype]
    if resolve(ctype) in STRUCTS:
        return ctype
    return None


class Wrapper:
    def __init__(self, f):
        self.f = f
        self.params = []   # valk parameter declarations
        self.args = []     # C call arguments
        self.unsafe = False
        self.method_of = None
        self.note = ""


def plan(f):
    if not bindable(f) or f["name"].startswith(SKIP_PREFIXES):
        return None
    w = Wrapper(f)
    params = f.get("params", [])
    i = 0
    while i < len(params):
        p = params[i]
        ctype = p["type"].strip()
        name = arg_name(p["name"])
        nxt = params[i + 1] if i + 1 < len(params) else None
        if ctype == "const char *":
            w.params.append("{}: String".format(name))
            if (f["name"], p["name"]) in NULLABLE_STRINGS:
                w.args.append("{0}.bytes > 0 ? {0}.data_cstring : null".format(name))
                w.note = "An empty string uses raylib's default shader for that stage."
            else:
                w.args.append("{}.data_cstring".format(name))
            i += 1
            continue
        m = re.match(r"^(?:const )?(\w+(?: \w+)?) \*$", ctype)
        if m and is_count(nxt):
            elem = value_type(m.group(1))
            if elem is None:
                return None
            w.params.append("{}: local &[{}]".format(name, elem))
            w.args.append("{0}.length > 0 ? {0}.data : null".format(name))
            w.args.append("{}.length.to(i32)".format(name))
            w.unsafe = False
            i += 2
            continue
        if i == 0 and ctype.endswith(" *") and resolve(ctype[:-2]) in METHOD_STRUCTS:
            w.method_of = resolve(ctype[:-2])
            w.args.append("this.@cast(ptr)")
            i += 1
            continue
        vt = value_type(ctype)
        if vt is None:
            return None
        enum = enum_for(f["name"], p["name"]) if vt == "i32" else None
        if enum:
            w.params.append("{}: {}".format(name, enum))
            w.args.append("{}.to(i32)".format(name))
        else:
            w.params.append("{}: {}".format(name, vt))
            w.args.append(name)
        i += 1
    ret = f["returnType"].strip()
    if ret == "void":
        w.ret = ""
    elif ret == "const char *":
        w.ret = "String"
    else:
        w.ret = value_type(ret)
        if w.ret is None:
            return None
    return w


def method_name(w):
    name = w.f["name"]
    if name in METHOD_NAMES:
        return METHOD_NAMES[name]
    prefix = w.method_of
    method = snake(name[len(prefix):]) if name.startswith(prefix) else snake(name)
    if method in [snake(f["name"]) for f in STRUCTS[w.method_of]["fields"]]:
        raise Exception("{} clashes with a field of {}, name it in METHOD_NAMES".format(name, w.method_of))
    return method


def render(w, name, indent):
    out = [doc(w.f["description"], indent)]
    if w.note:
        out.append(indent + "///\n" + indent + "/// " + w.note + "\n")
    sig = "{}+ fn {}({})".format(indent, name, ", ".join(w.params))
    if w.ret:
        sig += " " + w.ret
    out.append(sig + " {\n")
    body = indent + "    "
    if w.unsafe:
        out.append(body + "@unsafe\n")
    call = "{}({})".format(w.f["name"], ", ".join(w.args))
    if w.ret == "String":
        out.append(body + "let text = {}\n".format(call))
        out.append(body + 'return isset(text) ? text.to_string() : ""\n')
    elif w.ret:
        out.append(body + "return {}\n".format(call))
    else:
        out.append(body + call + "\n")
    out.append(indent + "}\n")
    return "".join(out)


def gen_wrappers():
    functions = [HEADER, "\n"]
    methods = {}
    for f in API["functions"]:
        w = plan(f)
        if w is None:
            continue
        if w.method_of:
            methods.setdefault(w.method_of, []).append(render(w, method_name(w), "    "))
        else:
            functions.append(render(w, snake(f["name"]), ""))
    write("functions.valk", "".join(functions))
    out = [HEADER]
    for struct, items in methods.items():
        out.append("\nextend {} {{\n".format(struct))
        out.append("\n".join(items))
        out.append("}\n")
    write("methods.valk", "".join(out))


def dummy(vtype):
    if vtype in NUMBERS.values() and vtype != "bool":
        return "0"
    if vtype == "bool":
        return "false"
    if vtype == "String":
        return '""'
    m = re.match(r"^local &\[(\w+)\]$", vtype)
    if m:
        elem = m.group(1)
        return "Array[{}]{{}}".format(elem if elem in NUMBERS.values() else "raylib." + elem)
    if vtype in ENUMS:
        return "raylib.{}.{}".format(vtype, enum_members(ENUMS[vtype])[0][0])
    return ".{}"


def gen_calls():
    out = [HEADER.replace("src/", "tests/"), "use raylib\nuse valk.core\n\n"]
    out.append("// Every generated wrapper, called once so each body is compiled. It never runs:\n")
    out.append("// most of them need a window, and some would close it.\n")
    out.append("fn call_every_wrapper() {\n")
    for n, f in enumerate(API["functions"]):
        w = plan(f)
        if w is None:
            continue
        args = ", ".join(dummy(p.split(": ", 1)[1]) for p in w.params)
        if w.method_of:
            var = "{}_{}".format(snake(w.method_of), n)
            out.append("    let {} = raylib.{}{{}}\n".format(var, w.method_of))
            out.append("    {}.{}({})\n".format(var, method_name(w), args))
        else:
            out.append("    raylib.{}({})\n".format(snake(f["name"]), args))
    out.append("}\n\n")
    out.append('test "Every generated wrapper compiles" {\n')
    out.append('    if (core.getenv("VALK_RAYLIB_CALL_EVERYTHING") !? "") == "yes" : call_every_wrapper()\n')
    out.append("}\n")
    with open(os.path.join(ROOT, "tests", "generated-calls.valk"), "w") as f:
        f.write("".join(out))


gen_types()
gen_enums()
gen_externs()
gen_wrappers()
gen_calls()
